<?php

namespace Database\Seeders;

use App\Models\Indikator;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IndikatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $indikator = [
            ['tujuan_id' => 1, 'kode_indikator' => '1.A.1', 'nama_indikator' => 'Persentase penduduk yang hidup di bawah garis kemiskinan nasional, menurut jenis kelamin dan kelompok umur.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.B.1', 'nama_indikator' => 'Proporsi dari penduduk dewasa yang mendapatkan hak atas tanah yang didasari oleh dokumen hukum dan yang memiliki hak atas tanah berdasarkan jenis kelamin dan tipe kepemilikan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.C.1.1', 'nama_indikator' => 'Persentase imunisasi dasar pada penduduk usia 12 - 23 bulan, terjadi deprivasi jika ada penduduk usia 12-23 tahun yang tidak mendapatkan imunisasi dasar.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.4.1(f)', 'nama_indikator' => 'Persentase luas wilayah kumuh perkotaan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.a.1', 'nama_indikator' => 'Proporsi sumber daya yang dialokasikan oleh pemerintah secara langsung untuk program pemberantasan kemiskinan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.4.1(k)', 'nama_indikator' => 'Persentase rumah tangga miskin dan rentan yang sumber penerangan utamanya listrik baik dari PLN dan bukan PLN. (kelompok penduduk 40% terbawah)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.3.1(c)', 'nama_indikator' => 'Persentase penyandang disabilitas yang miskin dan rentan yang terpenuhi hak dasarnya dan inklusivitas.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 1, 'kode_indikator' => '1.3.1(d)', 'nama_indikator' => 'Jumlah rumah tangga yang mendapatkan bantuan tunai bersyarat/Program Keluarga Harapan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.A.1', 'nama_indikator' => 'Prevalensi stunting (pendek dan sangat pendek) pada anak di bawah lima tahun/ balita.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.A.2', 'nama_indikator' => 'Prevalensi wasting (berat badan/tinggi badan) anak pada usia kurang dari 5 tahun, berdasarkan tipe.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.B.1', 'nama_indikator' => 'Luas LP2B (Lahan Pertanian Pangan Berkelanjutan)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.B.2', 'nama_indikator' => 'Jumlah inisiatif urban farming', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.C.1', 'nama_indikator' => 'Indikator Anomali Harga Pangan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.D.1', 'nama_indikator' => 'Prevalensi Ketidakcukupan Konsumsi Pangan (Prevalence of Undernourishment).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.1.2*', 'nama_indikator' => 'Prevalensi penduduk dengan kerawanan pangan sedang atau berat, berdasarkan pada Skala Pengalaman Kerawananan pangan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.1.2(a)', 'nama_indikator' => 'Proporsi penduduk dengan asupan kalori minimum di bawah 1.400 kkal/kapita/hari.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.2.2(a)', 'nama_indikator' => 'Prevalensi anemia pada ibu hamil', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.2.2(b)', 'nama_indikator' => 'Persentase bayi usia kurang dari 6 bulan yang mendapatkan ASI ekslusif.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 2, 'kode_indikator' => '2.2.2(c)', 'nama_indikator' => 'Tingkat konsumsi ikan per kapita', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.A.1', 'nama_indikator' => 'Angka Kematian Ibu (AKI).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.A.2.1', 'nama_indikator' => 'Proporsi perempuan pernah kawin umur 15-49 tahun yang proses melahirkan terakhirnya (a) ditolong oleh tenaga kesehatan terlatih', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.A.2.2', 'nama_indikator' => 'Proporsi perempuan pernah kawin umur 15-49 tahun yang proses melahirkan terakhirnya (b) di fasilitas kesehatan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.C.1', 'nama_indikator' => 'Jumlah tenaga kerja Kesehatan menurut jenis dibagi dengan jumlah penduduk kota pada tahun pelaporan kemudian di kali 1.000.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.C.2', 'nama_indikator' => 'Kematian dan cedera dalam kecelakaan lalu lintas (jumlah kematian dan cedera setiap 1.000 penduduk)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.C.3', 'nama_indikator' => 'Angka kematian bayi (Infant Mortality Rate) setiap 10.000 kelahiran hidup', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.D.1', 'nama_indikator' => 'Cakupan Jaminan Kesehatan Nasional (JKN)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.E.1', 'nama_indikator' => 'Persentase merokok pada penduduk umur diatas 15 tahun', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.2.2.(a)', 'nama_indikator' => 'Angka Kematian Balita (AKBa) per 1000 kelahiran hidup', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.3.1.(a)', 'nama_indikator' => 'Prevalensi HIV pada populasi dewasa', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.3.3*', 'nama_indikator' => 'Kejadian Malaria per 1000 orang', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.4.1.(c)', 'nama_indikator' => 'Prevalensi obesitas pada penduduk umur ≥18 tahun', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.4.2.(a)', 'nama_indikator' => 'Jumlah  puskesmas yang menyelenggarakan upaya kesehatan jiwa.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.5.1(a)', 'nama_indikator' => 'Jumlah penyalahguna narkotika dan pengguna alkohol yang merugikan, yang mengakses layanan rehabilitasi medis', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.5.1.(e)', 'nama_indikator' => 'Prevalensi penyalahgunaan narkoba', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 3, 'kode_indikator' => '3.b.1.(a)', 'nama_indikator' => 'Persentase ketersediaan obat dan vaksin di puskesmas', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.A.1.1', 'nama_indikator' => 'Rasio Angka Partisipasi Murni (APM) SD/Sederajat', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.A.1.2', 'nama_indikator' => 'Rasio Angka Partisipasi Murni (APM) SMP/Sederajat', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.A.2.1', 'nama_indikator' => 'Rasio Angka Partisipasi Kasar (APK) SD/Sederajat', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.A.2.2', 'nama_indikator' => 'Rasio Angka Partisipasi Kasar (APK) SMP/Sederajat', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.B.1', 'nama_indikator' => 'Persentase angka melek aksara penduduk umur diatas 15 tahun.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.C.1.1', 'nama_indikator' => 'Jumlah sekolah yang menyediakan akses listrik per total sekolah tingkat SMP dan SMA/SMK/setara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.C.1.2', 'nama_indikator' => 'Jumlah sekolah yang menyediakan akses internet untuk tujuan pengajaran per total sekolah tingkat SMP dan SMA/SMK/setara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.C.1.3', 'nama_indikator' => 'Jumlah sekolah yang menyediakan akses komputer untuk tujuan pengajaran per total sekolah tingkat SMP dan SMA/SMK/setara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.C.1.4', 'nama_indikator' => 'Jumlah sekolah yang menyediakan fasilitas sanitasi per total sekolah tingkat SMP dan SMA/SMK/setara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.C.1.5', 'nama_indikator' => 'Jumlah sekolah yang menyediakan fasilitas cuci tangan (terdiri dari air, sanitasi dan higenis bagi semua ) / WASH per total sekolah tingkat SMP dan SMA/SMK/setara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.D.1.1', 'nama_indikator' => 'Jumlah guru SD yang terkualifikasi per jumlah guru SD yang mengajar', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.D.1.2', 'nama_indikator' => 'Jumlah guru SMP yang terkualifikasi per jumlah guru SMP yang mengajar', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.1.1.(g)', 'nama_indikator' => 'Rata-rata lama sekolah penduduk umur ≥15 tahun', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.1.1.(a)', 'nama_indikator' => 'Persentase SD/MI berakreditasi minimal B', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 4, 'kode_indikator' => '4.1.1.(b)', 'nama_indikator' => 'Persentase SMP/MTs berakreditasi minimal B', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.A.1', 'nama_indikator' => 'Persentase pegawai Pemda baru gender perempuan per total pegawai Pemda baru ditempatkan pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.A.2', 'nama_indikator' => 'Persentase kelompok disabilitas yang baru direkrut terhadap total pegawai Pemda baru di rekrut pada tahun pelaporan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.B.1', 'nama_indikator' => 'Persentase pegawai perempuan yang mengambil cuti melahirkan terhadap total pegawai perempuan yang memperoleh hak cuti', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.C.1', 'nama_indikator' => 'Proporsi individu yang memiliki telepon genggam diperoleh dengan cara membagi jumlah individu yang menguasai/memiliki telepon genggam dengan jumlah penduduk pada periode yang sama dan dinyatakan dalam satuan persen (%).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.1.1*', 'nama_indikator' => 'Jumlah kebijakan yang responsif gender mendukung pemberdayaan perempuan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.2.1*', 'nama_indikator' => 'Proporsi perempuan dewasa dan anak perempuan (umur 15-64 tahun) mengalami kekerasan (fisik, seksual, atau emosional) oleh pasangan atau mantan pasangan dalam 12 bulan terakhir', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 5, 'kode_indikator' => '5.2.2.(a)', 'nama_indikator' => 'Persentase korban kekerasan terhadap perempuan yang mendapat layanan komprehensif.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 6, 'kode_indikator' => '6.A.1', 'nama_indikator' => 'Persentase rumah tangga yang menggunakan layanan air minum yang dikelola secara aman.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 6, 'kode_indikator' => '6.B.1', 'nama_indikator' => 'Persentase rumah tangga yang memiliki fasilitas cuci tangan dengan sabun dan air', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 6, 'kode_indikator' => '6.B.2', 'nama_indikator' => 'Persentase rumah tangga yang memiliki akses terhadap sanitasi layak', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 6, 'kode_indikator' => '6.2.1(b)', 'nama_indikator' => 'Persentase rumah tangga dengan tangki septik/ SPAL/ IPAL', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 6, 'kode_indikator' => '6.2.1 (f)', 'nama_indikator' => 'Jumlah rumah tangga yang terlayani sistem pengelolaan air limbah terpusat', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 7, 'kode_indikator' => '7.A.3', 'nama_indikator' => 'Persentase dari selisih pemakaian energi tahun 2023 ke 2022 terhadap pemakaian tahun 2023', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 7, 'kode_indikator' => '7.1.1(a).1', 'nama_indikator' => 'Konsumsi Listrik Per Kapita', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 7, 'kode_indikator' => '7.1.1(a).2', 'nama_indikator' => 'Konsumsi Listrik Per Rumah Tangga', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.A.1', 'nama_indikator' => 'Laju pertumbuhan PDB per kapita.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.A.2', 'nama_indikator' => 'PDB per kapita.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.B.1', 'nama_indikator' => 'Total PNS perempuan dan laki-laki ditempatkan di kota pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.B.2', 'nama_indikator' => 'Total ASN perempuan dan laki-laki ditempatkan di kota pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.C.1', 'nama_indikator' => 'Total tenaga ahli perempuan dan laki-laki  direkrut oleh pemerintah kota/UPT pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.C.2', 'nama_indikator' => 'Total non-tenaga ahli perempuan dan laki-laki  direkrut oleh pemerintah kota/UPT pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.D.1.1', 'nama_indikator' => 'Total jumlah upah ASN laki-laki yang direkrut dibagi dengan total pegawai ASN laki-laki yang direkrut pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.D.1.2', 'nama_indikator' => 'Total jumlah upah ASN perempuan yang direkrut dibagi dengan total pegawai ASN perempuan yang direkrut pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.E.1', 'nama_indikator' => 'Perbandingan laki-laki dengan perempuan pada tingkat Walikota, wakil Walikota, dan Sekda pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.E.2', 'nama_indikator' => 'Jumlah laki-laki yang menjabat sebagai kepala dinas pada tahun pelaporan dibandingkan dengan jumlah perempuan yang menjabat sebagai kepala dinas pada tahun pelaporan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.E.3', 'nama_indikator' => 'Persentase pegawai disabilitas terhadap keseluruhan pegawai Pemda', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.F.1', 'nama_indikator' => 'Sistem tunjangan adalah tambahan yang diberikan di luar gaji pokok (pada indikator ini terkait keselamatan dan kesehatan kerja).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.G.1', 'nama_indikator' => 'Ada pelatihan simulasi keadaan gawat darurat kepada pegawai', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.H.1', 'nama_indikator' => 'Ada mekanisme pencegahan kecelakaan (pengecekan dan pengelolaan bangunan kantor dan alat kerja, APAR, tangga darurat)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.I', 'nama_indikator' => 'Tingkat pengangguran terbuka berdasarkan jenis kelamin dan kelompok umur.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.8.1(a)', 'nama_indikator' => 'Jumlah perusahaan yang menerapkan norma K3', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.9.1(b)', 'nama_indikator' => 'Jumlah wisatawan nusantara', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 8, 'kode_indikator' => '8.9.2*', 'nama_indikator' => 'Jumlah pekerja pada industri pariwisata dalam proporsi terhadap total pekerja', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 9, 'kode_indikator' => '9.A.1', 'nama_indikator' => 'Panjang jalan nasional yang memenuhi kategori kondisi baik (roughness index <4) dan sedang (roughness index <8) per total panjang jalan kota', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 9, 'kode_indikator' => '9.B.1', 'nama_indikator' => 'Laju pertumbuhan PDB industri manufaktur.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 9, 'kode_indikator' => '9.2.2*', 'nama_indikator' => 'Proporsi tenaga kerja pada sektor industri manufaktur.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 9, 'kode_indikator' => '9.2.1(a)', 'nama_indikator' => 'Laju pertumbuhan PDRB  Industri Pengolahan non migas', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 10, 'kode_indikator' => '10.A.1', 'nama_indikator' => 'Persentase penduduk miskin di daerah tertinggal.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 10, 'kode_indikator' => '10.A.4', 'nama_indikator' => 'Rasio Gini', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.A.1', 'nama_indikator' => 'Persentase rumah tangga yang memiliki akses terhadap hunian yang layak dan terjangkau', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.B.1', 'nama_indikator' => 'Persentase penduduk terlayani transportasi umum', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.C.1', 'nama_indikator' => 'Proporsi populasi penduduk kota yang tinggal di daerah kumuh, permukiman liar atau rumah yang tidak layak.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.D.1.1', 'nama_indikator' => 'Jumlah partikel kualitas udara SO2 (ppm)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.D.1.2', 'nama_indikator' => 'Jumlah partikel kualitas udara NO2 (ppm)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.D.1.3', 'nama_indikator' => 'Jumlah partikel kualitas udara O3 ( &micro;g/m3)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.D.2.1', 'nama_indikator' => 'Jumlah sampah kota yang terkelola (dibuang sesuai dengan alur penanganan sampah mulai dari TPS sampai ke TPA) per total sampah  dihasilkan (baik yang terkelola dengan yang tidak terkelola)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.D.2.2', 'nama_indikator' => 'Jumlah bank sampah yang dikelola baik oleh pemerintah, swasta, maupun perorangan di suatu kota pada tahun pelaporan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.F.1', 'nama_indikator' => 'Memiliki rencana pengurangan bencana daerah sesuai dengan PERMENDAGRI Nomor 101/2018', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 11, 'kode_indikator' => '11.E.1', 'nama_indikator' => 'Persentase luas ruang terbuka hijau terhadap total luas kota', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 12, 'kode_indikator' => '12.A.4', 'nama_indikator' => 'Proporsi anggaran pengadaan untuk  para pemasok lokal di tingkat UMKM *Kategori UMKM menurut Undang-Undang Nomor 20 Tahun 2008', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 12, 'kode_indikator' => '12.B.2', 'nama_indikator' => 'Proporsi Limbah Sampah Yang Ditangani / Diolah Berdasarkan Jenis Penanganannya / Pengolahannya.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 12, 'kode_indikator' => '12.6.1.(a)', 'nama_indikator' => 'Jumlah perusahaan yang menerapkan sertifikasi SNI ISO 14001.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 12, 'kode_indikator' => '12.8.1.(a)', 'nama_indikator' => 'Jumlah fasilitas publik yang menerapkan Standar Pelayanan Masyarakat (SPM) dan teregister.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 13, 'kode_indikator' => '13.A.1', 'nama_indikator' => 'Jumlah korban meninggal, hilang dan terkena dampak langsung bencana per 100.000 orang', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' =>13, 'kode_indikator' => '13.C.1', 'nama_indikator' => 'Mempunyai rencana atau strategi aksi iklim', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 13, 'kode_indikator' => '13.B.1', 'nama_indikator' => 'Jumlah emisi gas rumah kaca (GRK) per tahun', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 14, 'kode_indikator' => '14.b.1*', 'nama_indikator' => 'Jumlah nelayan yang terlindungi (jumlah pokdakan yang telah berbadan hukum)', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 15, 'kode_indikator' => '15.A.1', 'nama_indikator' => 'Proporsi kawasan hutan terhadap total luas lahan.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 15, 'kode_indikator' => '15.B.1', 'nama_indikator' => 'Proporsi luas lahan kritis yang direhabilitasi terhadap luas lahan keseluruhan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 15, 'kode_indikator' => '15.7.1.(a)', 'nama_indikator' => 'Persentase penyelesaian tindak pidana lingkungan hidup sampai dengan P21 dari jumlah kasus yang terjadi', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.A.1', 'nama_indikator' => 'Persentase instansi pemerintah yang mendapat opini Wajar Tanpa Pengecualian (WTP).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.A.2', 'nama_indikator' => 'Peringkat instansi pemerintah dengan skor Sistem Akuntabilias Kinerja Instansi Pemerintah (SAKIP)  diatas  B', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.A.3', 'nama_indikator' => 'Peringkat instansi pemerintah dengan Indeks RB diatas  B', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.A.4', 'nama_indikator' => 'Jumlah Instansi pemerintah dengan tingkat kepatuhan pelayanan publik kategori baik.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.B.1', 'nama_indikator' => 'Proporsi anak umur di bawah 5 tahun yang kelahirannya dicatat oleh lembaga pencatatan sipil, menurut umur.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.C.1', 'nama_indikator' => 'Rencana Aksi Daerah (RAD) terkait program SDGs', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.C.2', 'nama_indikator' => 'Laporan Tahunan SDGs', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.C.3', 'nama_indikator' => 'Peraturan daerah yang masih berlaku terkait pelaksanaan SDGs', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.C.4', 'nama_indikator' => 'SK Penunjukan kesekretariatan SDGs yang masih berlaku', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.D.1.1', 'nama_indikator' => 'Rapat evaluasi akhir tahun diadakan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.E.1', 'nama_indikator' => 'Laporan Tahunan SDGs dibahas bersama/dilaporkan kepada Walikota', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.G.1', 'nama_indikator' => 'Jumlah aduan terkait insiden korupsi ditangani.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.G.2', 'nama_indikator' => 'Jumlah total insiden yang terbukti yang mengakibatkan pegawai diberikan sanksi karena korupsi', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.G.3', 'nama_indikator' => 'Jumlah total insiden yang terbukti yang mengakibatkan pegawai diberhentikan karena korupsi', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.H.1', 'nama_indikator' => 'Jumlah kasus kejahatan pembunuhan pada satu tahun terakhir.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.J', 'nama_indikator' => 'Persentase keterwakilan perempuan di Dewan Perwakilan Rakyat (DPR) dan Dewan Perwakilan Rakyat Daerah (DPRD).', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.1.3 (a)', 'nama_indikator' => 'Proporsi penduduk yang menjadi korban kejahatan kekerasan dalam 12 bulan terakhir', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 16, 'kode_indikator' => '16.2.1.(b)', 'nama_indikator' => 'Prevalensi kekerasan terhadap anak laki-laki dan anak perempuan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 17, 'kode_indikator' => '17.A.3', 'nama_indikator' => 'Proporsi anggaran daerah yang didanai oleh pajak daerah.', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
            ['tujuan_id' => 17, 'kode_indikator' => '17.B.1.1', 'nama_indikator' => 'total dana untuk pengembangan infrastruktur pendidikan dibagi total RABD per tahun pelaporan', 'tipe' => '%', 'created_at'=> now(), 'updated_at'=> now()],
        ];
        Indikator::query()->insert($indikator);
    }
}
